server:
  port: 9000

logging:
  level:
    root: INFO
    '[qinjus.productms]': DEBUG

app:
  product-service:
    host: localhost
    port: 8001
  recommendation-service:
    host: localhost
    port: 8002
  review-service:
    host: localhost
    port: 8003
